export const PROVINCES = [
  "Aceh",
  "Sumatera Utara",
  "Sumatera Barat",
  "Riau",
  "Jambi",
  "Sumatera Selatan",
  "Bengkulu",
  "Lampung",
  "Kepulauan Bangka Belitung",
  "Kepulauan Riau",
  "DKI Jakarta",
  "Jawa Barat",
  "Jawa Tengah",
  "DI Yogyakarta",
  "Jawa Timur",
  "Banten",
  "Bali",
  "Nusa Tenggara Barat",
  "Nusa Tenggara Timur",
  "Kalimantan Barat",
  "Kalimantan Tengah",
  "Kalimantan Selatan",
  "Kalimantan Timur",
  "Kalimantan Utara",
  "Sulawesi Utara",
  "Sulawesi Tengah",
  "Sulawesi Selatan",
  "Sulawesi Tenggara",
  "Sulawesi Barat",
  "Maluku",
  "Maluku Utara",
  "Papua",
  "Papua Barat",
]

export const CITIES_BY_PROVINCE: Record<string, string[]> = {
  Aceh: ["Banda Aceh", "Lhokseumawe", "Sabang", "Langsa", "Meulaboh"],
  "Sumatera Utara": ["Medan", "Binjai", "Pematang Siantar", "Tebing Tinggi", "Deli Serdang", "Karo", "Langkat"],
  "Sumatera Barat": ["Padang", "Bukittinggi", "Payakumbuh", "Sawahlunto", "Padang Panjang"],
  Riau: ["Pekanbaru", "Dumai", "Siak", "Rokan Hilir", "Rohul"],
  Jambi: ["Jambi", "Sungai Penuh", "Batang Hari", "Muaro Jambi", "Tebo"],
  "Sumatera Selatan": ["Palembang", "Prabumulih", "Lubuk Linggau", "OKI", "Musi Banyuasin"],
  Bengkulu: ["Bengkulu", "Curup", "Manna", "Seluma", "Kepahiang"],
  Lampung: ["Bandar Lampung", "Metro", "Lampung Tengah", "Lampung Utara", "Way Kanan"],
  "Kepulauan Bangka Belitung": ["Pangkal Pinang", "Sungai Liat", "Tanjung Pandan", "Belitung"],
  "Kepulauan Riau": ["Batam", "Tanjung Pinang", "Karimun", "Natuna", "Lingga"],
  "DKI Jakarta": [
    "Jakarta Pusat",
    "Jakarta Utara",
    "Jakarta Barat",
    "Jakarta Selatan",
    "Jakarta Timur",
    "Kepulauan Seribu",
  ],
  "Jawa Barat": [
    "Bandung",
    "Bekasi",
    "Bogor",
    "Cirebon",
    "Depok",
    "Garut",
    "Sukabumi",
    "Tasikmalaya",
    "Purwakarta",
    "Karawang",
    "Subang",
    "Indramayu",
  ],
  "Jawa Tengah": [
    "Semarang",
    "Solo",
    "Purwokerto",
    "Kudus",
    "Salatiga",
    "Tegal",
    "Magelang",
    "Pekalongan",
    "Batang",
    "Purbalingga",
    "Wonosobo",
    "Cilacap",
  ],
  "DI Yogyakarta": ["Yogyakarta", "Bantul", "Sleman", "Gunung Kidul", "Kulon Progo"],
  "Jawa Timur": [
    "Surabaya",
    "Malang",
    "Gresik",
    "Sidoarjo",
    "Mojokerto",
    "Blitar",
    "Batu",
    "Pasuruan",
    "Jombang",
    "Madiun",
    "Nganjuk",
    "Tulungagung",
    "Lumajang",
    "Bondowoso",
    "Situbondo",
  ],
  Banten: ["Tangerang", "Serang", "Cilegon", "Pandeglang", "Lebak"],
  Bali: ["Denpasar", "Badung", "Gianyar", "Tabanan", "Bangli", "Karangasem", "Buleleng", "Jembrana", "Klungkung"],
  "Nusa Tenggara Barat": [
    "Mataram",
    "Bima",
    "Lombok Timur",
    "Lombok Tengah",
    "Lombok Utara",
    "Sumbawa",
    "Sumbawa Barat",
  ],
  "Nusa Tenggara Timur": [
    "Kupang",
    "Dili",
    "Flores Timur",
    "Sikka",
    "Ende",
    "Ngada",
    "Manggarai",
    "Rote Ndao",
    "Timor Tengah Utara",
  ],
  "Kalimantan Barat": ["Pontianak", "Singkawang", "Mempawah", "Sanggau", "Sambas", "Kubu Raya", "Ketapang", "Sekadau"],
  "Kalimantan Tengah": [
    "Palangka Raya",
    "Sampit",
    "Kuala Kapuas",
    "Tamiang Layang",
    "Buntok",
    "Muara Teweh",
    "Pangkalan Bun",
  ],
  "Kalimantan Selatan": ["Banjarmasin", "Banjarbaru", "Martapura", "Amuntai", "Pelaihari"],
  "Kalimantan Timur": ["Samarinda", "Balikpapan", "Bontang", "Tenggarong", "Tarakan", "Berau", "Malinau", "Nunukan"],
  "Kalimantan Utara": ["Tanjung Selor", "Tarakan", "Bulungan", "Malinau", "Nunukan"],
  "Sulawesi Utara": ["Manado", "Bitung", "Tomohon", "Minahasa", "Sangihe", "Talaud"],
  "Sulawesi Tengah": ["Palu", "Gorontalo", "Donggala", "Banggai", "Buol", "Parigi Moutong", "Tojo Una-Una"],
  "Sulawesi Selatan": [
    "Makassar",
    "Parepare",
    "Palopo",
    "Maros",
    "Gowa",
    "Takalar",
    "Jeneponto",
    "Bantaeng",
    "Bulukumba",
    "Sinjai",
    "Bone",
    "Soppeng",
    "Wajo",
    "Sidrap",
    "Pinrang",
  ],
  "Sulawesi Tenggara": ["Kendari", "Baubau", "Konawe", "Konawe Utara", "Muna", "Buton", "Wakatobi"],
  "Sulawesi Barat": ["Mamuju", "Majene", "Polewali Mandar"],
  Maluku: ["Ambon", "Tual", "Seram Utara", "Maluku Tengah", "Maluku Tenggara", "Buru", "Seram Bagian Barat"],
  "Maluku Utara": ["Ternate", "Tidore", "Halmahera Utara", "Halmahera Tengah", "Halmahera Selatan", "Pulau Morotai"],
  Papua: [
    "Jayapura",
    "Sorong",
    "Merauke",
    "Manokwari",
    "Wamena",
    "Nabire",
    "Fakfak",
    "Kaimana",
    "Sarmi",
    "Yapen Waropen",
  ],
  "Papua Barat": ["Sorong", "Manokwari", "Fakfak", "Kaimana", "Teluk Wondama", "Maybrat", "Tambrauw"],
}

export function getCitiesByProvince(province: string): string[] {
  return CITIES_BY_PROVINCE[province] || []
}

export function searchProvinces(query: string): string[] {
  return PROVINCES.filter((prov) => prov.toLowerCase().includes(query.toLowerCase()))
}

export function searchCities(province: string, query: string): string[] {
  const cities = CITIES_BY_PROVINCE[province] || []
  return cities.filter((city) => city.toLowerCase().includes(query.toLowerCase()))
}
